version: '3'

services:

  haproxy:
    image: sanu28221/k8s_assi02:haproxy_image
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"

  node1.web:
    image: sanu28221/k8s_assi02:web_image

    volumes:
      - "./web/web.nginx.cfg:/etc/nginx/nginx.conf"
      - "./web/html:/usr/share/nginx/html"

  node1.api:
    image: sanu28221/k8s_assi02:node1api_image
    volumes:
      - "./api/node1.api.nginx.cfg:/etc/nginx/nginx.conf"

  node2.api:
    image: sanu28221/k8s_assi02:node1api_image
    volumes:
      - "./api/node2.api.nginx.cfg:/etc/nginx/nginx.conf"

  node3.api:
    image: sanu28221/k8s_assi02:node1api_image
    volumes:
      - "./api/node3.api.nginx.cfg:/etc/nginx/nginx.conf"
