apiVersion: v1
kind: Service
metadata:
  name: haproxy-svc
spec:
  selector:
    app: haproxy
  ports:
    - name: port01
      protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30007
    - name: port02
      protocol: "TCP"
      port: 8404
      targetPort: 8404
      nodePort: 30010
  type: NodePort